services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - monitoring
    environment:
      - EXTERNAL_SERVICE_API_URL=http://web:8000  # URL твоей API (замени порт если нужно)
    volumes:
      - ./logs:/app/logs  # Для хранения логов бота (если нужно)

networks:
  monitoring:
    external: true
    name: seeonline
